package services

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"aliang.one/nursorgate/common/cache"
)

// The phone conversation list used to show raw Claude Code meta wrappers as
// titles — `<local-command-caveat> Caveat: The messages below were generated
// by the user…`, `<command-name>/goal</command-name>…` — whenever a session
// had no /rename: 37% of this machine's transcripts open with such a meta
// message as their first user turn. These tests pin that meta wrappers are
// skipped at every title adoption point in favor of the first real user
// message (or no title at all, letting downstream placeholders win).

const junkCaveatMessage = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user expresses an explicit request.</local-command-caveat>"

// TestCollectClaudeVibeSessionsSkipsCaveatFirstMessage is the regression for
// the phone-visible junk titles: the transcript-derived title must come from
// the first real user message, not the caveat wrapper.
func TestCollectClaudeVibeSessionsSkipsCaveatFirstMessage(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("USERPROFILE", home)
	cache.ResetCacheDirForTest()

	projectPath := filepath.Join(home, "work", "myproject")
	require.NoError(t, os.MkdirAll(projectPath, 0o700))
	encodedCwd := "-" + strings.ReplaceAll(strings.Trim(projectPath, string(filepath.Separator)), string(filepath.Separator), "-")
	claudeDir := filepath.Join(home, ".claude", "projects", encodedCwd)
	require.NoError(t, os.MkdirAll(claudeDir, 0o700))

	userLine := func(text string) string {
		return `{"timestamp":"2026-06-13T02:00:00Z","type":"user","cwd":"` + projectPath +
			`","sessionId":"caveat-sid","gitBranch":"main","message":{"role":"user","content":` +
			mustJSONString(text) + `}}` + "\n"
	}
	transcript := userLine(junkCaveatMessage) + userLine("帮我修复登录页面的崩溃")
	require.NoError(t, os.WriteFile(filepath.Join(claudeDir, "caveat-sid.jsonl"), []byte(transcript), 0o600))

	sessions := collectClaudeVibeSessions(nil)
	found := findCollectedSession(sessions, "caveat-sid")
	require.NotNil(t, found)
	assert.Equal(t, "帮我修复登录页面的崩溃", found.Title)
	assert.NotContains(t, found.Title, "local-command-caveat")
}

// TestCollectClaudeVibeSessionsIndexJunkFirstPromptNotTitle pins the index
// fallback: with no customTitle and no summary, a slash-command invocation
// firstPrompt must not become the title (empty is better than junk).
func TestCollectClaudeVibeSessionsIndexJunkFirstPromptNotTitle(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("USERPROFILE", home)
	cache.ResetCacheDirForTest()

	projectPath := filepath.Join(home, "work", "proj")
	encodedCwd := "-" + strings.ReplaceAll(strings.Trim(projectPath, string(filepath.Separator)), string(filepath.Separator), "-")
	projectDir := filepath.Join(home, ".claude", "projects", encodedCwd)
	require.NoError(t, os.MkdirAll(projectDir, 0o700))
	index := map[string]interface{}{
		"originalPath": projectPath,
		"entries": []map[string]interface{}{
			{
				"sessionId":   "junk-fp-sid",
				"firstPrompt": "<command-name>/goal</command-name>\n<command-message>goal</command-message>\n<command-args>xxx</command-args>",
				"modified":    "2026-08-01T00:00:00Z",
			},
			{
				"sessionId":   "clean-sid",
				"summary":     "正常的自动摘要",
				"firstPrompt": "<command-name>/goal</command-name>\n<command-message>goal</command-message>",
				"modified":    "2026-08-01T00:00:00Z",
			},
		},
	}
	raw, err := json.Marshal(index)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(projectDir, "sessions-index.json"), raw, 0o600))

	sessions := collectClaudeVibeSessions(nil)
	junk := findCollectedSession(sessions, "junk-fp-sid")
	require.NotNil(t, junk)
	assert.NotContains(t, junk.Title, "<command-name>", "junk firstPrompt must never become the title")
	assert.Equal(t, "正常的自动摘要", findCollectedSession(sessions, "clean-sid").Title,
		"summary must still win over a junk firstPrompt")
}

// TestActiveVibeSessionsSnapshotSkipsJunkFirstMessage extends the same rule to
// phone-initiated managed sessions whose injected context lands in history
// before the user's real message.
func TestActiveVibeSessionsSnapshotSkipsJunkFirstMessage(t *testing.T) {
	manager := newAgentAIManager()
	manager.sessions["conv-1"] = &agentAISession{
		id:          "conv-1",
		projectPath: "/tmp/proj",
		cancel:      func() {},
		history: []agentAIMessage{
			{Role: "user", Content: junkCaveatMessage, CreatedAt: time.Now()},
			{Role: "user", Content: "真正的会话目标", CreatedAt: time.Now()},
		},
	}

	snapshot := manager.activeVibeSessionsSnapshot()
	require.Len(t, snapshot, 1)
	assert.Equal(t, "真正的会话目标", snapshot[0].Title)
	assert.NotContains(t, snapshot[0].Title, "local-command-caveat")
}

func mustJSONString(s string) string {
	raw, err := json.Marshal(s)
	if err != nil {
		panic(err)
	}
	return string(raw)
}
