package routes

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	auth "aliang.one/nursorgate/processor/auth"
	"aliang.one/nursorgate/processor/config"
)

func TestRunStopAndCertHTTPIntegration(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)

	stopReq := httptest.NewRequest(http.MethodPost, "/api/run/stop", bytes.NewReader([]byte(`{}`)))
	stopReq.Header.Set("Content-Type", "application/json")
	stopRec := httptest.NewRecorder()
	mux.ServeHTTP(stopRec, stopReq)

	if stopRec.Code != http.StatusOK {
		t.Fatalf("run stop http status=%d body=%s", stopRec.Code, stopRec.Body.String())
	}

	var stopResp map[string]interface{}
	if err := json.Unmarshal(stopRec.Body.Bytes(), &stopResp); err != nil {
		t.Fatalf("decode run stop response failed: %v", err)
	}

	stopData, _ := stopResp["data"].(map[string]interface{})
	if stopData["error"] != "not_running" {
		t.Fatalf("expected run stop error=not_running, got %#v", stopData["error"])
	}

	exportReq := httptest.NewRequest(http.MethodPost, "/api/cert/export", bytes.NewReader([]byte(`{"cert_type":"mitm-ca"}`)))
	exportReq.Header.Set("Content-Type", "application/json")
	exportRec := httptest.NewRecorder()
	mux.ServeHTTP(exportRec, exportReq)

	if exportRec.Code != http.StatusOK {
		t.Fatalf("cert export http status=%d body=%s", exportRec.Code, exportRec.Body.String())
	}

	statusReq := httptest.NewRequest(http.MethodGet, "/api/cert/status?cert_type=mitm-ca", nil)
	statusRec := httptest.NewRecorder()
	mux.ServeHTTP(statusRec, statusReq)

	if statusRec.Code != http.StatusOK {
		t.Fatalf("cert status http status=%d body=%s", statusRec.Code, statusRec.Body.String())
	}

	var statusResp map[string]interface{}
	if err := json.Unmarshal(statusRec.Body.Bytes(), &statusResp); err != nil {
		t.Fatalf("decode cert status response failed: %v", err)
	}

	statusData, _ := statusResp["data"].(map[string]interface{})
	if statusData["cert_type"] != "mitm-ca" {
		t.Fatalf("expected cert_type=mitm-ca, got %#v", statusData["cert_type"])
	}

	downloadReq := httptest.NewRequest(http.MethodGet, "/api/cert/download?cert_type=mitm-ca", nil)
	downloadRec := httptest.NewRecorder()
	mux.ServeHTTP(downloadRec, downloadReq)

	if downloadRec.Code != http.StatusOK {
		t.Fatalf("cert download http status=%d body=%s", downloadRec.Code, downloadRec.Body.String())
	}

	if contentDisposition := downloadRec.Header().Get("Content-Disposition"); !strings.Contains(contentDisposition, "mitm-ca.pem") {
		t.Fatalf("unexpected Content-Disposition: %s", contentDisposition)
	}
}

func TestAPIDocsAutoGeneratedFromRoutes(t *testing.T) {
	prevIsDev := isDev
	isDev = false
	t.Cleanup(func() {
		isDev = prevIsDev
	})

	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)

	jsonReq := httptest.NewRequest(http.MethodGet, "/api-docs/openapi.json", nil)
	jsonRec := httptest.NewRecorder()
	mux.ServeHTTP(jsonRec, jsonReq)

	if jsonRec.Code != http.StatusOK {
		t.Fatalf("openapi status=%d body=%s", jsonRec.Code, jsonRec.Body.String())
	}

	if contentType := jsonRec.Header().Get("Content-Type"); !strings.Contains(contentType, "application/json") {
		t.Fatalf("unexpected openapi content-type: %s", contentType)
	}

	body := jsonRec.Body.String()
	if !strings.Contains(body, "\"/api/run/start\"") {
		t.Fatalf("openapi missing expected route /api/run/start: %s", body)
	}
	if !strings.Contains(body, "\"/api/cert/import\"") || !strings.Contains(body, "\"/api/cert/rollback\"") {
		t.Fatalf("openapi missing custom certificate management routes: %s", body)
	}

	if !strings.Contains(body, "\"/api/chat/completions\"") {
		t.Fatalf("openapi missing expected route /api/chat/completions: %s", body)
	}

	if strings.Contains(body, "\"/api/chat/completions\":{\"delete\":") {
		t.Fatalf("openapi should not include unsupported DELETE method for /api/chat/completions: %s", body)
	}

	if !strings.Contains(body, "\"/api/chat/completions\":{\"post\":") {
		t.Fatalf("openapi should include POST method for /api/chat/completions: %s", body)
	}

	if !strings.Contains(body, "\"/api/config/customer\":{\"get\":") {
		t.Fatalf("openapi should include GET method for /api/config/customer: %s", body)
	}

	if !strings.Contains(body, "\"/api/config/customer\":{\"get\":") || !strings.Contains(body, "\"post\":") || !strings.Contains(body, "\"put\":") {
		t.Fatalf("openapi should include GET/POST/PUT methods for /api/config/customer: %s", body)
	}

	if !strings.Contains(body, "\"summary\":\"POST /api/chat/completions\"") {
		t.Fatalf("openapi should include summary for POST /api/chat/completions: %s", body)
	}

	if strings.Contains(body, "\"/api/config/core\"") {
		t.Fatalf("openapi should not include dev-only /api/config/core when isDev=false: %s", body)
	}

	if !strings.Contains(body, "\"requestBody\":") {
		t.Fatalf("openapi should include requestBody for body-capable methods: %s", body)
	}

	uiReq := httptest.NewRequest(http.MethodGet, "/api-docs/index.html", nil)
	uiRec := httptest.NewRecorder()
	mux.ServeHTTP(uiRec, uiReq)

	if uiRec.Code != http.StatusOK {
		t.Fatalf("swagger ui status=%d body=%s", uiRec.Code, uiRec.Body.String())
	}

	if !strings.Contains(uiRec.Body.String(), "SwaggerUIBundle") {
		t.Fatalf("swagger ui page not rendered correctly")
	}
}

func TestCoreConfigRouteNotRegisteredWhenNonDev(t *testing.T) {
	prevIsDev := isDev
	isDev = false
	t.Cleanup(func() {
		isDev = prevIsDev
	})

	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)

	req := httptest.NewRequest(http.MethodGet, "/api/config/core", nil)
	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, req)

	if rec.Code != http.StatusNotFound {
		t.Fatalf("expected 404 for non-dev core-config route, got %d body=%s", rec.Code, rec.Body.String())
	}
}

func TestCoreConfigRouteRegisteredWhenDev(t *testing.T) {
	prevIsDev := isDev
	isDev = true
	t.Cleanup(func() {
		isDev = prevIsDev
	})

	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)

	req := httptest.NewRequest(http.MethodGet, "/api/config/core", nil)
	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200 for dev core-config route, got %d body=%s", rec.Code, rec.Body.String())
	}

	var resp map[string]interface{}
	if err := json.Unmarshal(rec.Body.Bytes(), &resp); err != nil {
		t.Fatalf("decode core-config response failed: %v", err)
	}
	if _, ok := resp["code"]; !ok {
		t.Fatalf("expected standard envelope code field: %v", resp)
	}
	if _, ok := resp["msg"]; !ok {
		t.Fatalf("expected standard envelope msg field: %v", resp)
	}
	data, ok := resp["data"].(map[string]interface{})
	if !ok {
		t.Fatalf("expected standard envelope data object: %v", resp)
	}
	if _, ok := data["core"]; !ok {
		t.Fatalf("expected core field in data: %v", data)
	}
}

func TestAuthLegacyRoutesRemovedAndCanonicalRoutesRegistered(t *testing.T) {
	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)

	legacyPaths := []string{
		"/api/auth/activate",
		"/api/auth/userinfo",
		"/api/auth/refresh-status",
	}

	for _, path := range legacyPaths {
		req := httptest.NewRequest(http.MethodGet, path, nil)
		rec := httptest.NewRecorder()
		mux.ServeHTTP(rec, req)
		if rec.Code != http.StatusNotFound {
			t.Fatalf("expected legacy route %s to be removed with 404, got %d body=%s", path, rec.Code, rec.Body.String())
		}
	}

	canonicalPaths := []struct {
		path   string
		method string
	}{
		{path: "/api/auth/login", method: http.MethodPost},
		{path: "/api/auth/session", method: http.MethodGet},
		{path: "/api/auth/refresh", method: http.MethodPost},
		{path: "/api/auth/me", method: http.MethodGet},
		{path: "/api/auth/logout", method: http.MethodPost},
	}

	for _, route := range canonicalPaths {
		req := httptest.NewRequest(route.method, route.path, bytes.NewReader([]byte(`{}`)))
		rec := httptest.NewRecorder()
		mux.ServeHTTP(rec, req)
		if rec.Code == http.StatusNotFound {
			t.Fatalf("expected canonical route %s to be registered, got 404", route.path)
		}
	}
}

func TestAuthSessionAndUserCenterLifecycleIntegration(t *testing.T) {
	baseDir := t.TempDir()
	t.Setenv("HOME", baseDir)
	t.Setenv("ALIANG_CACHE_DIR", baseDir)

	auth.ResetAuthPersistenceForTest()
	authority := auth.ResetSessionAuthorityForTest()
	config.ResetGlobalConfigForTest()
	t.Cleanup(func() {
		auth.ResetAuthPersistenceForTest()
		auth.ResetSessionAuthorityForTest()
		config.ResetGlobalConfigForTest()
	})

	config.SetGlobalConfig(&config.Config{})

	h := NewHandlers()
	mux := http.NewServeMux()
	RegisterRoutes(h, mux)
	bootstrapReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/session", nil)
	bootstrapReq.RemoteAddr = "127.0.0.1:39999"
	bootstrapRec := httptest.NewRecorder()
	mux.ServeHTTP(bootstrapRec, bootstrapReq)
	if bootstrapRec.Code != http.StatusOK {
		t.Fatalf("dashboard session bootstrap status=%d body=%s", bootstrapRec.Code, bootstrapRec.Body.String())
	}
	dashboardCookies := bootstrapRec.Result().Cookies()
	if len(dashboardCookies) != 1 {
		t.Fatalf("dashboard session bootstrap cookies=%#v", dashboardCookies)
	}

	sessionReq := httptest.NewRequest(http.MethodGet, "/api/auth/session", nil)
	sessionReq.RemoteAddr = "127.0.0.1:40000"
	sessionReq.AddCookie(dashboardCookies[0])
	sessionRec := httptest.NewRecorder()
	mux.ServeHTTP(sessionRec, sessionReq)
	if sessionRec.Code != http.StatusOK {
		t.Fatalf("auth session status=%d body=%s", sessionRec.Code, sessionRec.Body.String())
	}

	var sessionResp map[string]interface{}
	if err := json.Unmarshal(sessionRec.Body.Bytes(), &sessionResp); err != nil {
		t.Fatalf("decode auth session response failed: %v", err)
	}
	sessionData, _ := sessionResp["data"].(map[string]interface{})
	if sessionData["state"] != "restoring" || sessionData["outcome"] != "session_recovering" {
		t.Fatalf("expected restoring snapshot, got %#v", sessionData)
	}
	initialRevision := sessionData["revision"]

	profileReq := httptest.NewRequest(http.MethodGet, "/api/user-center/profile", nil)
	profileRec := httptest.NewRecorder()
	mux.ServeHTTP(profileRec, profileReq)
	if profileRec.Code != http.StatusOK {
		t.Fatalf("user-center profile status=%d body=%s", profileRec.Code, profileRec.Body.String())
	}

	var profileResp map[string]interface{}
	if err := json.Unmarshal(profileRec.Body.Bytes(), &profileResp); err != nil {
		t.Fatalf("decode user-center profile response failed: %v", err)
	}
	profileData, _ := profileResp["data"].(map[string]interface{})
	if profileData["status"] != "unauthenticated" {
		t.Fatalf("expected unauthenticated profile status, got %#v", profileData["status"])
	}

	userInfo := &auth.UserInfo{
		AccessToken:  "",
		RefreshToken: "",
		TokenType:    "Bearer",
		Username:     "restored-user",
		Email:        "restored@example.com",
		Status:       "active",
		UpdatedAt:    time.Now(),
	}
	if err := auth.SaveUserInfo(userInfo); err != nil {
		t.Fatalf("failed to save persisted auth user info: %v", err)
	}

	secondSessionReq := httptest.NewRequest(http.MethodGet, "/api/auth/session", nil)
	secondSessionReq.RemoteAddr = "127.0.0.1:40001"
	secondSessionReq.AddCookie(dashboardCookies[0])
	secondSessionRec := httptest.NewRecorder()
	mux.ServeHTTP(secondSessionRec, secondSessionReq)
	if secondSessionRec.Code != http.StatusOK {
		t.Fatalf("auth session restore status=%d body=%s", secondSessionRec.Code, secondSessionRec.Body.String())
	}

	var secondSessionResp map[string]interface{}
	if err := json.Unmarshal(secondSessionRec.Body.Bytes(), &secondSessionResp); err != nil {
		t.Fatalf("decode auth session restore response failed: %v", err)
	}
	secondSessionData, _ := secondSessionResp["data"].(map[string]interface{})
	if secondSessionData["state"] != "restoring" || secondSessionData["revision"] != initialRevision {
		t.Fatalf("pure session read mutated or restored authority: %#v", secondSessionData)
	}
	if _, ok := secondSessionData["user"]; ok {
		t.Fatalf("restoring snapshot exposed persisted user before coordinator commit: %#v", secondSessionData)
	}

	// Session restoration is owned by the boot coordinator, not by GET.
	authority.NotifyLoggedIn(userInfo)
	activeSessionReq := httptest.NewRequest(http.MethodGet, "/api/auth/session", nil)
	activeSessionReq.RemoteAddr = "127.0.0.1:40002"
	activeSessionReq.AddCookie(dashboardCookies[0])
	activeSessionRec := httptest.NewRecorder()
	mux.ServeHTTP(activeSessionRec, activeSessionReq)
	if activeSessionRec.Code != http.StatusOK {
		t.Fatalf("active auth session status=%d body=%s", activeSessionRec.Code, activeSessionRec.Body.String())
	}
	var activeSessionResp map[string]interface{}
	if err := json.Unmarshal(activeSessionRec.Body.Bytes(), &activeSessionResp); err != nil {
		t.Fatalf("decode active auth session response failed: %v", err)
	}
	activeSessionData, _ := activeSessionResp["data"].(map[string]interface{})
	activeUser, _ := activeSessionData["user"].(map[string]interface{})
	if activeSessionData["state"] != "active" || activeUser["username"] != "restored-user" {
		t.Fatalf("expected coordinator-committed active snapshot, got %#v", activeSessionData)
	}

	meReq := httptest.NewRequest(http.MethodGet, "/api/auth/me", nil)
	meRec := httptest.NewRecorder()
	mux.ServeHTTP(meRec, meReq)
	if meRec.Code != http.StatusOK {
		t.Fatalf("auth me status=%d body=%s", meRec.Code, meRec.Body.String())
	}
	var meResp map[string]interface{}
	if err := json.Unmarshal(meRec.Body.Bytes(), &meResp); err != nil {
		t.Fatalf("decode auth me response failed: %v", err)
	}
	meData, _ := meResp["data"].(map[string]interface{})
	if meData["status"] != "success" {
		t.Fatalf("expected auth me success status, got %#v", meData["status"])
	}
	mePayload, _ := meData["data"].(map[string]interface{})
	if mePayload["username"] != "restored-user" {
		t.Fatalf("expected auth me username=restored-user, got %#v", mePayload["username"])
	}
	if got := mePayload["expires_in"]; got != nil && got != float64(0) {
		t.Fatalf("expected default expires_in to remain zero for restored session without expiry metadata, got %#v", got)
	}

	logoutReq := httptest.NewRequest(http.MethodPost, "/api/auth/logout", bytes.NewReader([]byte(`{}`)))
	logoutReq.Header.Set("Content-Type", "application/json")
	logoutRec := httptest.NewRecorder()
	mux.ServeHTTP(logoutRec, logoutReq)
	if logoutRec.Code != http.StatusOK {
		t.Fatalf("auth logout status=%d body=%s", logoutRec.Code, logoutRec.Body.String())
	}
	var logoutResp map[string]interface{}
	if err := json.Unmarshal(logoutRec.Body.Bytes(), &logoutResp); err != nil {
		t.Fatalf("decode logout response failed: %v", err)
	}
	logoutData, _ := logoutResp["data"].(map[string]interface{})
	if logoutData["status"] != "success" {
		t.Fatalf("expected logout success status, got %#v", logoutData["status"])
	}

	persisted, err := auth.HasPersistedUserInfo()
	if err != nil {
		t.Fatalf("failed to check persisted user info after logout: %v", err)
	}
	if persisted {
		t.Fatalf("expected persisted user info to be removed after logout")
	}

	meAfterLogoutReq := httptest.NewRequest(http.MethodGet, "/api/auth/me", nil)
	meAfterLogoutRec := httptest.NewRecorder()
	mux.ServeHTTP(meAfterLogoutRec, meAfterLogoutReq)
	if meAfterLogoutRec.Code != http.StatusOK {
		t.Fatalf("auth me after logout status=%d body=%s", meAfterLogoutRec.Code, meAfterLogoutRec.Body.String())
	}
	var meAfterLogoutResp map[string]interface{}
	if err := json.Unmarshal(meAfterLogoutRec.Body.Bytes(), &meAfterLogoutResp); err != nil {
		t.Fatalf("decode auth me after logout response failed: %v", err)
	}
	meAfterLogoutData, _ := meAfterLogoutResp["data"].(map[string]interface{})
	if meAfterLogoutData["status"] != "no_user" {
		t.Fatalf("expected no_user status after logout, got %#v", meAfterLogoutData["status"])
	}

	usageReq := httptest.NewRequest(http.MethodGet, "/api/user-center/usage/summary", nil)
	usageRec := httptest.NewRecorder()
	mux.ServeHTTP(usageRec, usageReq)
	if usageRec.Code != http.StatusOK {
		t.Fatalf("user-center usage status=%d body=%s", usageRec.Code, usageRec.Body.String())
	}
	var usageResp map[string]interface{}
	if err := json.Unmarshal(usageRec.Body.Bytes(), &usageResp); err != nil {
		t.Fatalf("decode user-center usage response failed: %v", err)
	}
	usageData, _ := usageResp["data"].(map[string]interface{})
	if usageData["status"] != "unauthenticated" {
		t.Fatalf("expected unauthenticated usage status after logout, got %#v", usageData["status"])
	}

}
